apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: demo-localhost
  namespace: default
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - backend:
          service:
            name: my-svc
            port:
              number: 80
        path: /
        pathType: Prefix
status:
  loadBalancer: {}
